# Generated by Django 5.1.1 on 2024-10-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_options_alter_link_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.unit'),
            preserve_default=False,
        ),
    ]
