# Generated by Django 5.1.1 on 2024-10-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_task_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
